name: List Dev Container Features
description: 📃 List all features in a monorepo in a GitHub Action
branding:
  icon: list
  color: blue
inputs:
  path:
    default: .
  ref: {}
  base-ref: {}
outputs:
  features:
    value: ${{ steps.main.outputs.features }}
  changed-features:
    value: ${{ steps.main.outputs.changed-features }}
  relevant-features:
    value: ${{ steps.main.outputs.relevant-features }}
runs:
  using: composite
  steps:
    - id: main
      run: '"$GITHUB_ACTION_PATH/mainw"'
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_BASE_REF: ${{ inputs.base-ref }}
        GITHUB_EVENT: ${{ toJSON(github.event) }}
