name: Test action
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - .gitattributes
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - .gitattributes
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: main
        uses: ./
        with:
          path: test
      - run: echo "$MAIN_OUTPUTS_ALL_FEATURES" | jq
        env:
          MAIN_OUTPUTS_ALL_FEATURES: ${{ steps.main.outputs.all-features }}
      - run: echo "$MAIN_OUTPUTS_CHANGED_FEATURES" | jq
        env:
          MAIN_OUTPUTS_CHANGED_FEATURES: ${{ steps.main.outputs.changed-features }}
      - run: echo "$MAIN_OUTPUTS_RELEVANT_FEATURES" | jq
        env:
          MAIN_OUTPUTS_RELEVANT_FEATURES: ${{ steps.main.outputs.relevant-features }}
